### ISSUE TITLE
Add option to include <!DOCTYPE html> declaration in rendered output

### ISSUE THREAD

**Issue by ethanbradley** [Michael-F-Ellis/htmltree#6]
Hi,

I've come across a situation where I need the `renderToFile` function to include `<!DOCTYPE> html` at the beginning of the file.

I have added the functionality to the `render` and `renderToFile` functions with a flag, `doctype_declaration`, defaulting to `False` for backwards compatibility. I have included an example below. I will submit a PR for this but if there is a better way to implement this, I'm happy to work on it.

```
>>> doc = Html()
>>> doc.render(doctype_declaration=True)
<!DOCTYPE html><html></html>
```

Thanks,
Ethan

**Comment by Michael-F-Ellis** [comment]
Approved and merged. Thanks!
